version: '2'
services:
    lender-app:
        image: lender
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mariadb://lender-mariadb:3306/lender
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    lender-mariadb:
        extends:
            file: mariadb.yml
            service: lender-mariadb
